project_id = "ncicvnojifvyidetoynt"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.deadline-notifications]
verify_jwt = true

[functions.send-custom-alert]
verify_jwt = true

[functions.send-meeting-notification]
verify_jwt = true